build:
  maxIssues: 100

complexity:
  LargeClass:
    excludes: ['**/test/**']
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Inject']
  TooManyFunctions:
    active: false

formatting:
  active: true
  autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: false

style:
  WildcardImport:
    active: false